openapi: 3.0.0
info:
  title: Auth Service API
  description: OpenAPI specification for the Auth Service, handling user authentication and health checks.
  version: 0.1.0
servers:
  - url: http://localhost:8002
    description: Development server
  - url: http://authservice:8002
    description: Production server
paths:
  /health:
    get:
      summary: Check the health status of the Auth Service.
      operationId: checkHealth
      responses:
        "200":
          description: Service is healthy.
          content:
            text/plain:
              schema:
                type: string
                example: OK
  /login:
    post:
      summary: Authenticate a user and generate a JWT token.
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: Username of the user (minimum 3 characters).
                  example: student
                  minLength: 3
                password:
                  type: string
                  description: Password of the user (minimum 3 characters).
                  example: pass
                  minLength: 3
      responses:
        "200":
          description: Login successful, returns JWT token and user information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT token for authenticated user.
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWY3NTZkYjNmYTIyZDIyN2E0YjdjN2QiLCJpYXQiOjE3MTA3MDg3NDUsImV4cCI6MTcxMDcxMjM0NX0.VMG_5DOyQ4GYlJQRcu1I6ICG1IGzuo2Xuei093ONHxw
                  userId:
                    type: string
                    description: Unique identifier of the user.
                    example: 65f756db3fa22d227a4b7c7d
                  username:
                    type: string
                    description: Username of the user.
                    example: student
        "400":
          description: Invalid input data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing validation issues.
                    example: Missing required field username
        "401":
          description: Invalid credentials.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
                    example: Invalid credentials
        "500":
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
                    example: Internal Server Error